version: "3.8"

services:
  flask-backend:
    build: ./flask-backend
    volumes:
      - /home/ubuntu/data/flask-backend:/app/data
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  socket-server:
    build: ./socket-server
    volumes:
      - /home/ubuntu/data/flask-backend:/app/data
    ports:
      - "8888:8888"
    depends_on:
      flask-backend:
        condition: service_healthy
